//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieterP.ScoreSheet.Localization.Views.Wizards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieterP.ScoreSheet.Localization.Views.Wizards.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For non-official matches it is possible to play with pre-gift (better known as &apos;handicap&apos;). If you wish, you can select the handicap table that you want to use below.
        ///
        ///The handicap points will be printed on the referee score cards..
        /// </summary>
        public static string Handicap_Description {
            get {
                return ResourceManager.GetString("Handicap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play with pre-gift.
        /// </summary>
        public static string Handicap_UseHandicap {
            get {
                return ResourceManager.GetString("Handicap_UseHandicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose which game type you use for an unofficial match. The game type has an impact on what the score sheet looks like..
        /// </summary>
        public static string NewCustomMatch_Description {
            get {
                return ResourceManager.GetString("NewCustomMatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all the matches of a specific division on a given day.
        /// </summary>
        public static string NewDivisionDay_Description {
            get {
                return ResourceManager.GetString("NewDivisionDay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... loading data ....
        /// </summary>
        public static string NewDivisionDay_Loading {
            get {
                return ResourceManager.GetString("NewDivisionDay_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select for a given region a division and a date, and ScoreSheet will open all the corresponding matches (regardless of the clubs that are playing). This feature can be used for specific events (eg youth competition) where multiple matches of different clubs are played at one venue..
        /// </summary>
        public static string NewDivisionDay_Message {
            get {
                return ResourceManager.GetString("NewDivisionDay_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        public static string NewDivisionDay_National {
            get {
                return ResourceManager.GetString("NewDivisionDay_National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open division day.
        /// </summary>
        public static string NewDivisionDay_Title {
            get {
                return ResourceManager.GetString("NewDivisionDay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list below shows all available match days. Choose the match day for which you want to generate the score sheets and click on OK..
        /// </summary>
        public static string NewMatchday_Description {
            get {
                return ResourceManager.GetString("NewMatchday_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also open score sheets for away matches.
        /// </summary>
        public static string NewMatchday_OpenAway {
            get {
                return ResourceManager.GetString("NewMatchday_OpenAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bye matches that are scheduled this week.
        /// </summary>
        public static string NewMatchday_OpenBye {
            get {
                return ResourceManager.GetString("NewMatchday_OpenBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in series {0} {1} {2}.
        /// </summary>
        public static string OrphanedMatch_InSeries {
            get {
                return ResourceManager.GetString("OrphanedMatch_InSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is played in the week of.
        /// </summary>
        public static string OrphanedMatch_PlayedInWeek {
            get {
                return ResourceManager.GetString("OrphanedMatch_PlayedInWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some matches, the match date could not be determined automatically. Please confirm the correct match dates for these matches..
        /// </summary>
        public static string OrphanedMatches_Description {
            get {
                return ResourceManager.GetString("OrphanedMatches_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what you want to print from the selected match:.
        /// </summary>
        public static string Print_Description {
            get {
                return ResourceManager.GetString("Print_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use handicap.
        /// </summary>
        public static string Print_Handicap {
            get {
                return ResourceManager.GetString("Print_Handicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print_Print {
            get {
                return ResourceManager.GetString("Print_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match results.
        /// </summary>
        public static string Print_Results {
            get {
                return ResourceManager.GetString("Print_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee score cards.
        /// </summary>
        public static string Print_ScoreCards {
            get {
                return ResourceManager.GetString("Print_ScoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old match results were found in the backup directory of this program. These are usually files left behind after a program crash. You can open these score sheets again by selecting them and clicking on &apos;Repair&apos;..
        /// </summary>
        public static string RestoreBackups_Description {
            get {
                return ResourceManager.GetString("RestoreBackups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the match details that you can then upload to the competition website.
        /// </summary>
        public static string SelectExportType_Csv {
            get {
                return ResourceManager.GetString("SelectExportType_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can export the selected matches to multiple file types. Select the file type you want to export to below..
        /// </summary>
        public static string SelectExportType_Description {
            get {
                return ResourceManager.GetString("SelectExportType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains score sheets that can be viewed or printed via a PDF reader.
        /// </summary>
        public static string SelectExportType_Pdf {
            get {
                return ResourceManager.GetString("SelectExportType_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains score sheets that can be viewed or printed via an XPS reader.
        /// </summary>
        public static string SelectExportType_Xps {
            get {
                return ResourceManager.GetString("SelectExportType_Xps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a non-competitive match and should not be uploaded.
        /// </summary>
        public static string SelectMatches_NonCompetitiveMessage {
            get {
                return ResourceManager.GetString("SelectMatches_NonCompetitiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match has already been successfully uploaded to the competition website.
        /// </summary>
        public static string SelectMatches_UploadMessage {
            get {
                return ResourceManager.GetString("SelectMatches_UploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match contains validation errors.
        /// </summary>
        public static string SelectMatches_ValidationErrors {
            get {
                return ResourceManager.GetString("SelectMatches_ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players.
        /// </summary>
        public static string SelectPlayers_AllPlayers {
            get {
                return ResourceManager.GetString("SelectPlayers_AllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief referee.
        /// </summary>
        public static string SelectPlayers_ChiefReferee {
            get {
                return ResourceManager.GetString("SelectPlayers_ChiefReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant players.
        /// </summary>
        public static string SelectPlayers_RelevantPlayers {
            get {
                return ResourceManager.GetString("SelectPlayers_RelevantPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room commissioner.
        /// </summary>
        public static string SelectPlayers_RoomCommissioner {
            get {
                return ResourceManager.GetString("SelectPlayers_RoomCommissioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can update the data in the database of the program via this window. This data includes all information about the planned competition matches, as well as the member list of the home club and all visiting clubs.
        ///
        ///This data is best updated weekly, since in principle it can change every week (eg changes to the member lists). Outdated data can lead to errors on the match sheet, and therefore also to fines!.
        /// </summary>
        public static string UpdateFromInternet_Description {
            get {
                return ResourceManager.GetString("UpdateFromInternet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string UpdateFromInternet_Next {
            get {
                return ResourceManager.GetString("UpdateFromInternet_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the list.
        /// </summary>
        public static string UpdateFromInternet_RefreshList {
            get {
                return ResourceManager.GetString("UpdateFromInternet_RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your club:.
        /// </summary>
        public static string UpdateFromInternet_SelectClub {
            get {
                return ResourceManager.GetString("UpdateFromInternet_SelectClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your province:.
        /// </summary>
        public static string UpdateFromInternet_SelectProvince {
            get {
                return ResourceManager.GetString("UpdateFromInternet_SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating;
        ///please wait.
        /// </summary>
        public static string UpdateFromInternet_Updating {
            get {
                return ResourceManager.GetString("UpdateFromInternet_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update with an update file.
        /// </summary>
        public static string UpdateStart_File {
            get {
                return ResourceManager.GetString("UpdateStart_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an update file on a USB stick, and you want to use this file to bring the database up-to-date. This method can be used if this computer has no internet connection..
        /// </summary>
        public static string UpdateStart_FileDesc {
            get {
                return ResourceManager.GetString("UpdateStart_FileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I create an update file?.
        /// </summary>
        public static string UpdateStart_FileInfo {
            get {
                return ResourceManager.GetString("UpdateStart_FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update via the Internet.
        /// </summary>
        public static string UpdateStart_Internet {
            get {
                return ResourceManager.GetString("UpdateStart_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest data is downloaded from the KBTTB website. This is the simplest option, but requires an active internet connection..
        /// </summary>
        public static string UpdateStart_InternetDesc {
            get {
                return ResourceManager.GetString("UpdateStart_InternetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is now being downloaded from the KBTTB website. This process may take a while, depending on the size of your club and the speed of your internet connection..
        /// </summary>
        public static string UpdatingFromInternet_Description {
            get {
                return ResourceManager.GetString("UpdatingFromInternet_Description", resourceCulture);
            }
        }
    }
}
