//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieterP.ScoreSheet.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieterP.ScoreSheet.Localization.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was empty..
        /// </summary>
        public static string AbstractDatabase_FileEmpty {
            get {
                return ResourceManager.GetString("AbstractDatabase_FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hash of the downloaded file does not correspond to the expected hash. Try again later..
        /// </summary>
        public static string AppUpdate_InvalidHash {
            get {
                return ResourceManager.GetString("AppUpdate_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required match system ({0}) could not be found..
        /// </summary>
        public static string CompetitiveMatch_MatchSystemNotFound {
            get {
                return ResourceManager.GetString("CompetitiveMatch_MatchSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the away captain is invalid..
        /// </summary>
        public static string CsvExporter_InvalidIdAwayCaptain {
            get {
                return ResourceManager.GetString("CsvExporter_InvalidIdAwayCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the chief referee is invalid..
        /// </summary>
        public static string CsvExporter_InvalidIdChiefReferee {
            get {
                return ResourceManager.GetString("CsvExporter_InvalidIdChiefReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the home captain is invalid..
        /// </summary>
        public static string CsvExporter_InvalidIdHomeCaptain {
            get {
                return ResourceManager.GetString("CsvExporter_InvalidIdHomeCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id &apos;{0}&apos; for player {1} in the team {2}..
        /// </summary>
        public static string CsvExporter_InvalidIdPlayer {
            get {
                return ResourceManager.GetString("CsvExporter_InvalidIdPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the room commissioner is invalid..
        /// </summary>
        public static string CsvExporter_InvalidIdRoomCommissioner {
            get {
                return ResourceManager.GetString("CsvExporter_InvalidIdRoomCommissioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the Id of the current season. Update the database to correct this problem..
        /// </summary>
        public static string CsvExporter_InvalidSeasonId {
            get {
                return ResourceManager.GetString("CsvExporter_InvalidSeasonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club Id of the away team is invalid..
        /// </summary>
        public static string CsvExporter_NoClubIdAway {
            get {
                return ResourceManager.GetString("CsvExporter_NoClubIdAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club Id of the home team is invalid..
        /// </summary>
        public static string CsvExporter_NoClubIdHome {
            get {
                return ResourceManager.GetString("CsvExporter_NoClubIdHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match Id is invalid..
        /// </summary>
        public static string CsvExporter_NoMatchId {
            get {
                return ResourceManager.GetString("CsvExporter_NoMatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the template corresponding to the {0} viewmodel class..
        /// </summary>
        public static string ExportService_TemplateError {
            get {
                return ResourceManager.GetString("ExportService_TemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading a partial matchresult..
        /// </summary>
        public static string LiveUpdate_UploadError {
            get {
                return ResourceManager.GetString("LiveUpdate_UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception occurred..
        /// </summary>
        public static string Logger_UnknownError {
            get {
                return ResourceManager.GetString("Logger_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when opening the score sheet. More information can be found in the logbook..
        /// </summary>
        public static string Main_OpenError {
            get {
                return ResourceManager.GetString("Main_OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the score sheet. More information can be found in the logbook..
        /// </summary>
        public static string Main_SaveError {
            get {
                return ResourceManager.GetString("Main_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while contacting the server. Make sure your internet connection is working properly..
        /// </summary>
        public static string MatchUploader_GeneralError {
            get {
                return ResourceManager.GetString("MatchUploader_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find (valid) stored credentials in the database..
        /// </summary>
        public static string MatchUploader_NoCredentials {
            get {
                return ResourceManager.GetString("MatchUploader_NoCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PlayersToStringConverter] PlayerInfo was not single or double!.
        /// </summary>
        public static string PlayerstoString_DataError {
            get {
                return ResourceManager.GetString("PlayerstoString_DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watermark.
        /// </summary>
        public static string Settings_Watermark {
            get {
                return ResourceManager.GetString("Settings_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Category found for club {0} ({1}).
        /// </summary>
        public static string TabT_CategoryError {
            get {
                return ResourceManager.GetString("TabT_CategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown culture received: {0}. Returning default English..
        /// </summary>
        public static string TabT_CultureError {
            get {
                return ResourceManager.GetString("TabT_CultureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the database used by TabT is empty..
        /// </summary>
        public static string TabT_DatabaseNameEmpty {
            get {
                return ResourceManager.GetString("TabT_DatabaseNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse match information for match {0}.
        /// </summary>
        public static string TabT_MatchInfoError {
            get {
                return ResourceManager.GetString("TabT_MatchInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse one of the MatchSystem MatchDefinitions that was returned, for MatchDefinition at position &apos;{0}&apos;.
        /// </summary>
        public static string TabT_MatchSystemDefinitionError {
            get {
                return ResourceManager.GetString("TabT_MatchSystemDefinitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse one of the MatchSystem values that was returned, for MatchSystem &apos;{0}&apos; ({1}).
        /// </summary>
        public static string TabT_MatchSystemParseError {
            get {
                return ResourceManager.GetString("TabT_MatchSystemParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse member information for {0} {1}.
        /// </summary>
        public static string TabT_MemberError {
            get {
                return ResourceManager.GetString("TabT_MemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MatchDefinitions found in the MatchSystem &apos;{0}&apos; ({1}).
        /// </summary>
        public static string TabT_NoMatchDefinitionsError {
            get {
                return ResourceManager.GetString("TabT_NoMatchDefinitionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse allowed quota: {0}.
        /// </summary>
        public static string TabT_ParseAllowedQuotaError {
            get {
                return ResourceManager.GetString("TabT_ParseAllowedQuotaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse current quota: {0}.
        /// </summary>
        public static string TabT_ParseCurrentQuotaError {
            get {
                return ResourceManager.GetString("TabT_ParseCurrentQuotaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid season ID: &apos;{0}&apos; for season &apos;{1}&apos;.
        /// </summary>
        public static string TabT_SeasonIdError {
            get {
                return ResourceManager.GetString("TabT_SeasonIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of seasons is empty..
        /// </summary>
        public static string TabT_SeasonsWarning {
            get {
                return ResourceManager.GetString("TabT_SeasonsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned the following error: &apos;{0}&apos;. ScoreSheet will retry the download..
        /// </summary>
        public static string TabT_ServiceException {
            get {
                return ResourceManager.GetString("TabT_ServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid team data found for one of the teams in club {0}.
        /// </summary>
        public static string TabT_TeamDataError {
            get {
                return ResourceManager.GetString("TabT_TeamDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid VenueId/ClubVenueId found for club {0} ({1}).
        /// </summary>
        public static string TabT_VenueError {
            get {
                return ResourceManager.GetString("TabT_VenueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse version type received from web service: {0}.
        /// </summary>
        public static string TabT_VersionError {
            get {
                return ResourceManager.GetString("TabT_VersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading additional divisions.
        /// </summary>
        public static string TabTUpdater_AdditionalDivisionError {
            get {
                return ResourceManager.GetString("TabTUpdater_AdditionalDivisionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the division of match {0}..
        /// </summary>
        public static string TabTUpdater_CannotFindDivision {
            get {
                return ResourceManager.GetString("TabTUpdater_CannotFindDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the division {0} for match {1} of team {2}.
        /// </summary>
        public static string TabTUpdater_CannotFindDivisionWMatchWTeam {
            get {
                return ResourceManager.GetString("TabTUpdater_CannotFindDivisionWMatchWTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading division &apos;{0}&apos;.
        /// </summary>
        public static string TabTUpdater_DivisionError {
            get {
                return ResourceManager.GetString("TabTUpdater_DivisionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} has a match without date (and it&apos;s not a bye-match).
        /// </summary>
        public static string TabTUpdater_InvalidMatchDate {
            get {
                return ResourceManager.GetString("TabTUpdater_InvalidMatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating the matchdetails for team {0}.
        /// </summary>
        public static string TabTUpdater_MatchDetailsError {
            get {
                return ResourceManager.GetString("TabTUpdater_MatchDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the match system for type {0} (match {1} of team {2} in division {3}).
        /// </summary>
        public static string TabTUpdater_MatchSystemNotFound {
            get {
                return ResourceManager.GetString("TabTUpdater_MatchSystemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading the memberlist of club {0}.
        /// </summary>
        public static string TabTUpdater_MembersListError {
            get {
                return ResourceManager.GetString("TabTUpdater_MembersListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClubs returned an empty list of clubs..
        /// </summary>
        public static string TabTUpdater_NoClubs {
            get {
                return ResourceManager.GetString("TabTUpdater_NoClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClubs list contains a club without a unique id.
        /// </summary>
        public static string TabTUpdater_NoUniqueId {
            get {
                return ResourceManager.GetString("TabTUpdater_NoUniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet specifies that it is both men&apos;s and women&apos;s competition.
        /// </summary>
        public static string Validation_BothGenders {
            get {
                return ResourceManager.GetString("Validation_BothGenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captain of {0} cannot be a walkover.
        /// </summary>
        public static string Validation_CaptainNotWO {
            get {
                return ResourceManager.GetString("Validation_CaptainNotWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief referee of this match also plays in another simultaneous match ({0})..
        /// </summary>
        public static string Validation_ChiefRefereeNotAvailable {
            get {
                return ResourceManager.GetString("Validation_ChiefRefereeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief referee must not be a member of the away club.
        /// </summary>
        public static string Validation_ChiefRefereeNotAwayMember {
            get {
                return ResourceManager.GetString("Validation_ChiefRefereeNotAwayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief referee may not be a player other than the home captain.
        /// </summary>
        public static string Validation_ChiefRefereeNotHomeCaptain {
            get {
                return ResourceManager.GetString("Validation_ChiefRefereeNotHomeCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the club Id of {0} in the database.
        /// </summary>
        public static string Validation_ClubIdNotFound {
            get {
                return ResourceManager.GetString("Validation_ClubIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the match is invalid.
        /// </summary>
        public static string Validation_InvalidDate {
            get {
                return ResourceManager.GetString("Validation_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end hour is invalid.
        /// </summary>
        public static string Validation_InvalidEndHour {
            get {
                return ResourceManager.GetString("Validation_InvalidEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of {0} is invalid.
        /// </summary>
        public static string Validation_InvalidIndex {
            get {
                return ResourceManager.GetString("Validation_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player Id of {0} is invalid.
        /// </summary>
        public static string Validation_InvalidMemberId {
            get {
                return ResourceManager.GetString("Validation_InvalidMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the player Id of {0} is empty or invalid.
        /// </summary>
        public static string Validation_InvalidPlayerId {
            get {
                return ResourceManager.GetString("Validation_InvalidPlayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The players of {0} are not ordered correctly.
        /// </summary>
        public static string Validation_InvalidPlayerOrder {
            get {
                return ResourceManager.GetString("Validation_InvalidPlayerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player position of {0} is invalid.
        /// </summary>
        public static string Validation_InvalidPlayerPosition {
            get {
                return ResourceManager.GetString("Validation_InvalidPlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ranking of {0} is invalid.
        /// </summary>
        public static string Validation_InvalidRanking {
            get {
                return ResourceManager.GetString("Validation_InvalidRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the room commissioner is invalid.
        /// </summary>
        public static string Validation_InvalidRoomCommissionerId {
            get {
                return ResourceManager.GetString("Validation_InvalidRoomCommissionerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start hour is invalid.
        /// </summary>
        public static string Validation_InvalidStartHour {
            get {
                return ResourceManager.GetString("Validation_InvalidStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple match types selected.
        /// </summary>
        public static string Validation_MultipleMatchTypes {
            get {
                return ResourceManager.GetString("Validation_MultipleMatchTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address is empty.
        /// </summary>
        public static string Validation_NoAddress {
            get {
                return ResourceManager.GetString("Validation_NoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club Id of {0} is empty.
        /// </summary>
        public static string Validation_NoClubId {
            get {
                return ResourceManager.GetString("Validation_NoClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the match is empty.
        /// </summary>
        public static string Validation_NoDate {
            get {
                return ResourceManager.GetString("Validation_NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end hour is missing.
        /// </summary>
        public static string Validation_NoEndHour {
            get {
                return ResourceManager.GetString("Validation_NoEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet doesn&apos;t specify whether it is men&apos;s or women&apos;s competition.
        /// </summary>
        public static string Validation_NoGender {
            get {
                return ResourceManager.GetString("Validation_NoGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match Id is missing.
        /// </summary>
        public static string Validation_NoMatchId {
            get {
                return ResourceManager.GetString("Validation_NoMatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match type selected.
        /// </summary>
        public static string Validation_NoMatchType {
            get {
                return ResourceManager.GetString("Validation_NoMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of {0} is missing.
        /// </summary>
        public static string Validation_NoName {
            get {
                return ResourceManager.GetString("Validation_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the room commissioner is missing.
        /// </summary>
        public static string Validation_NoRoomCommissionerId {
            get {
                return ResourceManager.GetString("Validation_NoRoomCommissionerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the room commissioner is missing.
        /// </summary>
        public static string Validation_NoRoomCommissionerName {
            get {
                return ResourceManager.GetString("Validation_NoRoomCommissionerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The series is missing.
        /// </summary>
        public static string Validation_NoSeries {
            get {
                return ResourceManager.GetString("Validation_NoSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start hour is missing.
        /// </summary>
        public static string Validation_NoStartHour {
            get {
                return ResourceManager.GetString("Validation_NoStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields of {0}, except the player Id, must be empty for a bye match.
        /// </summary>
        public static string Validation_PlayerByeFieldsWrong {
            get {
                return ResourceManager.GetString("Validation_PlayerByeFieldsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player Id of {0} must be a question mark.
        /// </summary>
        public static string Validation_PlayerByeIdWrong {
            get {
                return ResourceManager.GetString("Validation_PlayerByeIdWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all fields of {0}, except the player Id, must be empty if you use a question mark as player Id.
        /// </summary>
        public static string Validation_PlayerFfFieldsWrong {
            get {
                return ResourceManager.GetString("Validation_PlayerFfFieldsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0} with player Id {1} in the member list.
        /// </summary>
        public static string Validation_PlayerNotFound {
            get {
                return ResourceManager.GetString("Validation_PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet contains invalid results.
        /// </summary>
        public static string Validation_ScoreError {
            get {
                return ResourceManager.GetString("Validation_ScoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet is not yet complete.
        /// </summary>
        public static string Validation_ScoreIncomplete {
            get {
                return ResourceManager.GetString("Validation_ScoreIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The level is set to &apos;super&apos;, but the corresponding check mark in the match types is missing.
        /// </summary>
        public static string Validation_SuperCheck {
            get {
                return ResourceManager.GetString("Validation_SuperCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one player can be WO in {0}.
        /// </summary>
        public static string Validation_TooManyWO {
            get {
                return ResourceManager.GetString("Validation_TooManyWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date on the score sheet does not correspond to the official date ({0}).
        /// </summary>
        public static string Validation_UnofficialDate {
            get {
                return ResourceManager.GetString("Validation_UnofficialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the match Id does not correpsond to the official data ({0}).
        /// </summary>
        public static string Validation_UnofficialMatchId {
            get {
                return ResourceManager.GetString("Validation_UnofficialMatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of {0} does not correspond to the official data.
        /// </summary>
        public static string Validation_UnofficialName {
            get {
                return ResourceManager.GetString("Validation_UnofficialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The series does not correspond to the official data ({0}).
        /// </summary>
        public static string Validation_UnofficialSeries {
            get {
                return ResourceManager.GetString("Validation_UnofficialSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date on the score sheet does not correspond to today&apos;s date.
        /// </summary>
        public static string Validation_WrongDate {
            get {
                return ResourceManager.GetString("Validation_WrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of {0} does not correspond to the data in the database.
        /// </summary>
        public static string Validation_WrongIndex {
            get {
                return ResourceManager.GetString("Validation_WrongIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of {0} does not correspond to the data in the database.
        /// </summary>
        public static string Validation_WrongName {
            get {
                return ResourceManager.GetString("Validation_WrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player position of {0} does not correspond to the data in the database.
        /// </summary>
        public static string Validation_WrongPlayerPosition {
            get {
                return ResourceManager.GetString("Validation_WrongPlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ranking of {0} does not correspond to the data in the database.
        /// </summary>
        public static string Validation_WrongRanking {
            get {
                return ResourceManager.GetString("Validation_WrongRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the room commissioner is invalid (or the room commissioner is not a member of the home team).
        /// </summary>
        public static string Validation_WrongRoomCommissionerId {
            get {
                return ResourceManager.GetString("Validation_WrongRoomCommissionerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dialog open at this time..
        /// </summary>
        public static string WindowService_NoDialogError {
            get {
                return ResourceManager.GetString("WindowService_NoDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the popup corresponding to the {0} viewmodel class..
        /// </summary>
        public static string WindowService_PopupError {
            get {
                return ResourceManager.GetString("WindowService_PopupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the window corresponding to the {0} viewmodel class..
        /// </summary>
        public static string WindowService_WindowError {
            get {
                return ResourceManager.GetString("WindowService_WindowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the club list. You may not have internet access, or the competition server is unreachable. You can find more information about this error in the log screen..
        /// </summary>
        public static string Wizard_ClubUpdateFailed {
            get {
                return ResourceManager.GetString("Wizard_ClubUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file could not be loaded! Check that you have selected the correct file..
        /// </summary>
        public static string Wizard_FileReadError {
            get {
                return ResourceManager.GetString("Wizard_FileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the data. You do not have the required permissions to upload this data. Use another account (with the required permissions) to upload the data, or contact the responsible of the competition to request the appropriate access rights..
        /// </summary>
        public static string Wizard_InvalidCredentials {
            get {
                return ResourceManager.GetString("Wizard_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User selected an entry on the NewMatchday window that was not a Match or DateTime.
        /// </summary>
        public static string Wizard_InvalidSelection {
            get {
                return ResourceManager.GetString("Wizard_InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network error occurred while uploading the data..
        /// </summary>
        public static string Wizard_NetworkError {
            get {
                return ResourceManager.GetString("Wizard_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the data. The server has detected a number of validation errors in the data..
        /// </summary>
        public static string Wizard_ServerError {
            get {
                return ResourceManager.GetString("Wizard_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the data. You may not have internet access, or the competition server is unreachable. You can find more information about this error in the log screen..
        /// </summary>
        public static string Wizard_UpdateError {
            get {
                return ResourceManager.GetString("Wizard_UpdateError", resourceCulture);
            }
        }
    }
}
