//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieterP.ScoreSheet.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieterP.ScoreSheet.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started on {0} at {1}.
        /// </summary>
        public static string App_ApplicationStarted {
            get {
                return ResourceManager.GetString("App_ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application stopped on {0} at {1}.
        /// </summary>
        public static string App_ApplicationStopped {
            get {
                return ResourceManager.GetString("App_ApplicationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of ScoreSheet is already active. You can only start one instance of ScoreSheet at a time..
        /// </summary>
        public static string App_MultipleInstances {
            get {
                return ResourceManager.GetString("App_MultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string App_UnknownError {
            get {
                return ResourceManager.GetString("App_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update contains an invalid action type..
        /// </summary>
        public static string AppUpdate_InvalidActionType {
            get {
                return ResourceManager.GetString("AppUpdate_InvalidActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hash was missing in the update info. Cannot verify file integrity..
        /// </summary>
        public static string AppUpdate_MissingHash {
            get {
                return ResourceManager.GetString("AppUpdate_MissingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update of the application has been installed. Restart the application to use the latest version..
        /// </summary>
        public static string AppUpdate_Restart {
            get {
                return ResourceManager.GetString("AppUpdate_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match backed up on disk on {0}.
        /// </summary>
        public static string CompetitiveMatch_MatchBackedUp {
            get {
                return ResourceManager.GetString("CompetitiveMatch_MatchBackedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match saved on disk on {0}.
        /// </summary>
        public static string CompetitiveMatch_MatchSaved {
            get {
                return ResourceManager.GetString("CompetitiveMatch_MatchSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} match(es).
        /// </summary>
        public static string ExportButton_Email {
            get {
                return ResourceManager.GetString("ExportButton_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} match(es).
        /// </summary>
        public static string ExportButton_Export {
            get {
                return ResourceManager.GetString("ExportButton_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload {0} match(es).
        /// </summary>
        public static string ExportButton_Upload {
            get {
                return ResourceManager.GetString("ExportButton_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official handicap table (men).
        /// </summary>
        public static string Handicap_Men {
            get {
                return ResourceManager.GetString("Handicap_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official handicap table (women).
        /// </summary>
        public static string Handicap_Women {
            get {
                return ResourceManager.GetString("Handicap_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom theme.
        /// </summary>
        public static string Layout_Custom {
            get {
                return ResourceManager.GetString("Layout_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Layout_Default {
            get {
                return ResourceManager.GetString("Layout_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-contrast.
        /// </summary>
        public static string Layout_HighContrast {
            get {
                return ResourceManager.GetString("Layout_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PieterP.be Theme.
        /// </summary>
        public static string Layout_PieterP {
            get {
                return ResourceManager.GetString("Layout_PieterP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Layout_Yellow {
            get {
                return ResourceManager.GetString("Layout_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        public static string LevelInfo_National {
            get {
                return ResourceManager.GetString("LevelInfo_National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincial.
        /// </summary>
        public static string LevelInfo_Provincial {
            get {
                return ResourceManager.GetString("LevelInfo_Provincial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional.
        /// </summary>
        public static string LevelInfo_Regional {
            get {
                return ResourceManager.GetString("LevelInfo_Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super.
        /// </summary>
        public static string LevelInfo_Super {
            get {
                return ResourceManager.GetString("LevelInfo_Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the mail server. Concult the logbook for more details..
        /// </summary>
        public static string Limburg_EmailError {
            get {
                return ResourceManager.GetString("Limburg_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the mail server was successful..
        /// </summary>
        public static string Limburg_EmailSent {
            get {
                return ResourceManager.GetString("Limburg_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while exporting the match results to PDF. Please consult the logbook for the details of the error..
        /// </summary>
        public static string Limburg_ExportError {
            get {
                return ResourceManager.GetString("Limburg_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while emailing the results. Please consult the logbook for the details of the error..
        /// </summary>
        public static string Limburg_ResultsError {
            get {
                return ResourceManager.GetString("Limburg_ResultsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email with the results has been successfully sent to {0}..
        /// </summary>
        public static string Limburg_ResultsSent {
            get {
                return ResourceManager.GetString("Limburg_ResultsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server validation errors:.
        /// </summary>
        public static string LiveUpdate_ServerErrors {
            get {
                return ResourceManager.GetString("LiveUpdate_ServerErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following CSV line was uploaded:.
        /// </summary>
        public static string LiveUpdate_Uploaded {
            get {
                return ResourceManager.GetString("LiveUpdate_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first time that you have started this version of ScoreSheet. Do you want to adjust the settings now?.
        /// </summary>
        public static string Main_FirstStart {
            get {
                return ResourceManager.GetString("Main_FirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is currently empty. Do you want to update it?.
        /// </summary>
        public static string Main_NoData {
            get {
                return ResourceManager.GetString("Main_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Main_Overview {
            get {
                return ResourceManager.GetString("Main_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSheet files.
        /// </summary>
        public static string Main_ScoreSheetFiles {
            get {
                return ResourceManager.GetString("Main_ScoreSheetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSheet update file.
        /// </summary>
        public static string Main_ScoreSheetUpdateFile {
            get {
                return ResourceManager.GetString("Main_ScoreSheetUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close these matches without uploading the results to the competition website?.
        /// </summary>
        public static string Main_UploadWarningFooter {
            get {
                return ResourceManager.GetString("Main_UploadWarningFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following official matches have been modified but have not yet been uploaded to the competition website:.
        /// </summary>
        public static string Main_UploadWarningHeader {
            get {
                return ResourceManager.GetString("Main_UploadWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} played a draw with {1}-{2}.
        /// </summary>
        public static string Match_Draw {
            get {
                return ResourceManager.GetString("Match_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        public static string Match_Empty {
            get {
                return ResourceManager.GetString("Match_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match is incomplete or contains errors.
        /// </summary>
        public static string Match_Invalid {
            get {
                return ResourceManager.GetString("Match_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has lost with {1}-{2}.
        /// </summary>
        public static string Match_Lost {
            get {
                return ResourceManager.GetString("Match_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} against {1} ({2}).
        /// </summary>
        public static string Match_MatchTitle {
            get {
                return ResourceManager.GetString("Match_MatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has won with {1}-{2}.
        /// </summary>
        public static string Match_Won {
            get {
                return ResourceManager.GetString("Match_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to away player {0}.
        /// </summary>
        public static string MatchSystem_AwayPlayer {
            get {
                return ResourceManager.GetString("MatchSystem_AwayPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup.
        /// </summary>
        public static string MatchSystem_Cup {
            get {
                return ResourceManager.GetString("MatchSystem_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisure competition.
        /// </summary>
        public static string MatchSystem_FreeTime {
            get {
                return ResourceManager.GetString("MatchSystem_FreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home player {0}.
        /// </summary>
        public static string MatchSystem_HomePlayer {
            get {
                return ResourceManager.GetString("MatchSystem_HomePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub Men.
        /// </summary>
        public static string MatchSystem_InterclubMen {
            get {
                return ResourceManager.GetString("MatchSystem_InterclubMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub Men (old system).
        /// </summary>
        public static string MatchSystem_InterclubMenOld {
            get {
                return ResourceManager.GetString("MatchSystem_InterclubMenOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub Women/Veterans.
        /// </summary>
        public static string MatchSystem_InterclubWomenVeterans {
            get {
                return ResourceManager.GetString("MatchSystem_InterclubWomenVeterans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub Women/Veterans (old system).
        /// </summary>
        public static string MatchSystem_InterclubWomenVeteransOld {
            get {
                return ResourceManager.GetString("MatchSystem_InterclubWomenVeteransOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super.
        /// </summary>
        public static string MatchSystem_Super {
            get {
                return ResourceManager.GetString("MatchSystem_Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super (old system, no substitute).
        /// </summary>
        public static string MatchSystem_SuperOld {
            get {
                return ResourceManager.GetString("MatchSystem_SuperOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the away captain.
        /// </summary>
        public static string MatchSystem_TheAwayCaptain {
            get {
                return ResourceManager.GetString("MatchSystem_TheAwayCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the away team.
        /// </summary>
        public static string MatchSystem_TheAwayTeam {
            get {
                return ResourceManager.GetString("MatchSystem_TheAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the chief referee.
        /// </summary>
        public static string MatchSystem_TheChiefReferee {
            get {
                return ResourceManager.GetString("MatchSystem_TheChiefReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the home captain.
        /// </summary>
        public static string MatchSystem_TheHomeCaptain {
            get {
                return ResourceManager.GetString("MatchSystem_TheHomeCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the home team.
        /// </summary>
        public static string MatchSystem_TheHomeTeam {
            get {
                return ResourceManager.GetString("MatchSystem_TheHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth (2x2).
        /// </summary>
        public static string MatchSystem_Youth {
            get {
                return ResourceManager.GetString("MatchSystem_Youth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} against {1}, {2} matches
        ///{3} winning sets to {4} points.
        /// </summary>
        public static string MatchSystemInfo_Description {
            get {
                return ResourceManager.GetString("MatchSystemInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;away&gt;.
        /// </summary>
        public static string MatchTracker_Away {
            get {
                return ResourceManager.GetString("MatchTracker_Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;home&gt;.
        /// </summary>
        public static string MatchTracker_Home {
            get {
                return ResourceManager.GetString("MatchTracker_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while updating the member list of club {0}.
        /// </summary>
        public static string MemberList_AutoUpdateFailed {
            get {
                return ResourceManager.GetString("MemberList_AutoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-update of {0} memberlist succeeded.
        /// </summary>
        public static string MemberList_AutoUpdateSucceeded {
            get {
                return ResourceManager.GetString("MemberList_AutoUpdateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away player.
        /// </summary>
        public static string PlayersToNames_AwayPlayer {
            get {
                return ResourceManager.GetString("PlayersToNames_AwayPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string PlayersToNames_Double {
            get {
                return ResourceManager.GetString("PlayersToNames_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home player.
        /// </summary>
        public static string PlayersToNames_HomePlayer {
            get {
                return ResourceManager.GetString("PlayersToNames_HomePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PlayersToNames_Player {
            get {
                return ResourceManager.GetString("PlayersToNames_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string PlayerType_FreeTime {
            get {
                return ResourceManager.GetString("PlayerType_FreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string PlayerType_RecreationalReserve {
            get {
                return ResourceManager.GetString("PlayerType_RecreationalReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Acrobat Reader could not be found at the standard locations..
        /// </summary>
        public static string Print_AcrobatNotFound {
            get {
                return ResourceManager.GetString("Print_AcrobatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Print_AllFiles {
            get {
                return ResourceManager.GetString("Print_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match you wish to print contains validation errors:.
        /// </summary>
        public static string Print_ValidationErrorsFound {
            get {
                return ResourceManager.GetString("Print_ValidationErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to print the match?.
        /// </summary>
        public static string PrintValidationErrorsContinue {
            get {
                return ResourceManager.GetString("PrintValidationErrorsContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout to cut (1x8).
        /// </summary>
        public static string RefereeLayout_1by8 {
            get {
                return ResourceManager.GetString("RefereeLayout_1by8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout to cut (2x4).
        /// </summary>
        public static string RefereeLayout_2by4 {
            get {
                return ResourceManager.GetString("RefereeLayout_2by4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One page per table.
        /// </summary>
        public static string RefereeLayout_PerTable {
            get {
                return ResourceManager.GetString("RefereeLayout_PerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee: away.
        /// </summary>
        public static string RefereeTemplate_RefereeAway {
            get {
                return ResourceManager.GetString("RefereeTemplate_RefereeAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee: away player {0}.
        /// </summary>
        public static string RefereeTemplate_RefereeAwayPlayer {
            get {
                return ResourceManager.GetString("RefereeTemplate_RefereeAwayPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee: home.
        /// </summary>
        public static string RefereeTemplate_RefereeHome {
            get {
                return ResourceManager.GetString("RefereeTemplate_RefereeHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee: home player {0}.
        /// </summary>
        public static string RefereeTemplate_RefereeHomePlayer {
            get {
                return ResourceManager.GetString("RefereeTemplate_RefereeHomePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore {0} matches.
        /// </summary>
        public static string RestoreBackup_RestoreMultiple {
            get {
                return ResourceManager.GetString("RestoreBackup_RestoreMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore nothing.
        /// </summary>
        public static string RestoreBackup_RestoreNothing {
            get {
                return ResourceManager.GetString("RestoreBackup_RestoreNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore 1 match.
        /// </summary>
        public static string RestoreBackup_RestoreOne {
            get {
                return ResourceManager.GetString("RestoreBackup_RestoreOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} against {1}.
        /// </summary>
        public static string RestoredMatch_Against {
            get {
                return ResourceManager.GetString("RestoredMatch_Against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        public static string RestoredMatch_Empty {
            get {
                return ResourceManager.GetString("RestoredMatch_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match #{0} that was played on {1}.
        /// </summary>
        public static string RestoredMatch_MatchInfo {
            get {
                return ResourceManager.GetString("RestoredMatch_MatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string ScoreVisualization_Compact {
            get {
                return ResourceManager.GetString("ScoreVisualization_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the results of all the ongoing matches in a single overview..
        /// </summary>
        public static string ScoreVisualization_CompactDesc {
            get {
                return ResourceManager.GetString("ScoreVisualization_CompactDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string ScoreVisualization_Default {
            get {
                return ResourceManager.GetString("ScoreVisualization_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows all the match details, one match at a time..
        /// </summary>
        public static string ScoreVisualization_DefaultDesc {
            get {
                return ResourceManager.GetString("ScoreVisualization_DefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the visualization that you want to use for the overview screen and the second screen..
        /// </summary>
        public static string ScoreVisualization_Message {
            get {
                return ResourceManager.GetString("ScoreVisualization_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview screen.
        /// </summary>
        public static string ScoreVisualization_OverviewScreen {
            get {
                return ResourceManager.GetString("ScoreVisualization_OverviewScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second screen.
        /// </summary>
        public static string ScoreVisualization_SecondScreen {
            get {
                return ResourceManager.GetString("ScoreVisualization_SecondScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary screen.
        /// </summary>
        public static string Screen_Primary {
            get {
                return ResourceManager.GetString("Screen_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a natural number..
        /// </summary>
        public static string SetScoreViewModel_NaturalNumber {
            get {
                return ResourceManager.GetString("SetScoreViewModel_NaturalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic upload.
        /// </summary>
        public static string Settings_AutoUpload {
            get {
                return ResourceManager.GetString("Settings_AutoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default values.
        /// </summary>
        public static string Settings_Defaults {
            get {
                return ResourceManager.GetString("Settings_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow away matches.
        /// </summary>
        public static string Settings_FollowAway {
            get {
                return ResourceManager.GetString("Settings_FollowAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Settings_Layout {
            get {
                return ResourceManager.GetString("Settings_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisure competition Limburg.
        /// </summary>
        public static string Settings_Limburg {
            get {
                return ResourceManager.GetString("Settings_Limburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Updates.
        /// </summary>
        public static string Settings_LiveUpdates {
            get {
                return ResourceManager.GetString("Settings_LiveUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string Settings_Printing {
            get {
                return ResourceManager.GetString("Settings_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score visualization.
        /// </summary>
        public static string Settings_ScoreVisualization {
            get {
                return ResourceManager.GetString("Settings_ScoreVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second screen.
        /// </summary>
        public static string Settings_SecondScreen {
            get {
                return ResourceManager.GetString("Settings_SecondScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup settings.
        /// </summary>
        public static string Settings_Startup {
            get {
                return ResourceManager.GetString("Settings_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Settings_Upload {
            get {
                return ResourceManager.GetString("Settings_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various.
        /// </summary>
        public static string Settings_Various {
            get {
                return ResourceManager.GetString("Settings_Various", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service.
        /// </summary>
        public static string Settings_WebService {
            get {
                return ResourceManager.GetString("Settings_WebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet contains unsaved modifications.
        /// </summary>
        public static string Status_Dirty {
            get {
                return ResourceManager.GetString("Status_Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results were successfully emailed to the responsibles of the leisure competition.
        /// </summary>
        public static string Status_Emailed {
            get {
                return ResourceManager.GetString("Status_Emailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet was successfully saved to disk.
        /// </summary>
        public static string Status_Saved {
            get {
                return ResourceManager.GetString("Status_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The score sheet was successfully uploaded to the competition server.
        /// </summary>
        public static string Status_Uploaded {
            get {
                return ResourceManager.GetString("Status_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while uploading the score sheet to the competition website. Retry the upload manually to see why it is failing..
        /// </summary>
        public static string Status_UploadError {
            get {
                return ResourceManager.GetString("Status_UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No substitution.
        /// </summary>
        public static string SubstitutePlayerInfo_NoSubstitute {
            get {
                return ResourceManager.GetString("SubstitutePlayerInfo_NoSubstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution in match #{0}.
        /// </summary>
        public static string SubstitutePlayerInfo_Substitute {
            get {
                return ResourceManager.GetString("SubstitutePlayerInfo_Substitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using API version {0}.
        /// </summary>
        public static string TabT_APIVersion {
            get {
                return ResourceManager.GetString("TabT_APIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the TabT database is &apos;{0}&apos;.
        /// </summary>
        public static string TabT_DatabaseName {
            get {
                return ResourceManager.GetString("TabT_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, {0} quota is used out of a total of {1}..
        /// </summary>
        public static string TabT_QuotaInfo {
            get {
                return ResourceManager.GetString("TabT_QuotaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added club {0} ({1}).
        /// </summary>
        public static string TabTUpdater_AddedClub {
            get {
                return ResourceManager.GetString("TabTUpdater_AddedClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional divisions downloaded.
        /// </summary>
        public static string TabTUpdater_AdditionalDivisionsDownloaded {
            get {
                return ResourceManager.GetString("TabTUpdater_AdditionalDivisionsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of the clubs begins.
        /// </summary>
        public static string TabTUpdater_BeginClubUpdate {
            get {
                return ResourceManager.GetString("TabTUpdater_BeginClubUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of the database begins.
        /// </summary>
        public static string TabTUpdater_BeginMatchUpdate {
            get {
                return ResourceManager.GetString("TabTUpdater_BeginMatchUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user canceled the update..
        /// </summary>
        public static string TabTUpdater_Canceled {
            get {
                return ResourceManager.GetString("TabTUpdater_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the update of the clubs has finished successfully..
        /// </summary>
        public static string TabTUpdater_ClubsUpdated {
            get {
                return ResourceManager.GetString("TabTUpdater_ClubsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded divisions.
        /// </summary>
        public static string TabTUpdater_DivisionsDownloaded {
            get {
                return ResourceManager.GetString("TabTUpdater_DivisionsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the data of season {0}.
        /// </summary>
        public static string TabTUpdater_DownloadingSeason {
            get {
                return ResourceManager.GetString("TabTUpdater_DownloadingSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string TabTUpdater_Finished {
            get {
                return ResourceManager.GetString("TabTUpdater_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match [{0} - {1} ({2})] can be found under the &apos;Matches with an unknown date&apos;!.
        /// </summary>
        public static string TabTUpdater_InvalidDateInfo {
            get {
                return ResourceManager.GetString("TabTUpdater_InvalidDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match details of team {0} in {1} downloaded.
        /// </summary>
        public static string TabTUpdater_MatchDetailsDownloaded {
            get {
                return ResourceManager.GetString("TabTUpdater_MatchDetailsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match {0} - {1} ({2}) will be planned in the week of {3}.
        /// </summary>
        public static string TabTUpdater_MatchPlanned {
            get {
                return ResourceManager.GetString("TabTUpdater_MatchPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member list of {0} downloaded.
        /// </summary>
        public static string TabTUpdater_MemberListDownloaded {
            get {
                return ResourceManager.GetString("TabTUpdater_MemberListDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincial (men-)member lists are downloaded.
        /// </summary>
        public static string TabTUpdater_MemberListsDownloaded {
            get {
                return ResourceManager.GetString("TabTUpdater_MemberListsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no teams from your club registered on the official KBTTB competition website yet. Try again later..
        /// </summary>
        public static string TabTUpdater_NoTeams {
            get {
                return ResourceManager.GetString("TabTUpdater_NoTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} from division &apos;{1}&apos; has a match where the week could not be found!.
        /// </summary>
        public static string TabTUpdater_NoWeek {
            get {
                return ResourceManager.GetString("TabTUpdater_NoWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation used the following web service calls: {0}.
        /// </summary>
        public static string TabTUpdater_Stats {
            get {
                return ResourceManager.GetString("TabTUpdater_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams van {0} gedownload.
        /// </summary>
        public static string TabTUpdater_TeamsDownloaded {
            get {
                return ResourceManager.GetString("TabTUpdater_TeamsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was not (completely) successful. You can find the details in the logs..
        /// </summary>
        public static string TabTUpdater_UpdateFailed {
            get {
                return ResourceManager.GetString("TabTUpdater_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of the matches was successful.
        /// </summary>
        public static string TabTUpdater_UpdateSucceeded {
            get {
                return ResourceManager.GetString("TabTUpdater_UpdateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: You have not yet entered a username/password. This may cause errors!.
        /// </summary>
        public static string TabTUpdater_Warning {
            get {
                return ResourceManager.GetString("TabTUpdater_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the update.
        /// </summary>
        public static string UpdateStatusToString_Downloading {
            get {
                return ResourceManager.GetString("UpdateStatusToString_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while checking for an update.
        /// </summary>
        public static string UpdateStatusToString_Error {
            get {
                return ResourceManager.GetString("UpdateStatusToString_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the update.
        /// </summary>
        public static string UpdateStatusToString_Installing {
            get {
                return ResourceManager.GetString("UpdateStatusToString_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string UpdateStatusToString_NoUpdate {
            get {
                return ResourceManager.GetString("UpdateStatusToString_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for an update.
        /// </summary>
        public static string UpdateStatusToString_Searching {
            get {
                return ResourceManager.GetString("UpdateStatusToString_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status.
        /// </summary>
        public static string UpdateStatusToString_Unknown {
            get {
                return ResourceManager.GetString("UpdateStatusToString_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application update succeeded! Restart the application..
        /// </summary>
        public static string UpdateStatusToString_Updated {
            get {
                return ResourceManager.GetString("UpdateStatusToString_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of the application is outdated. Please update the application..
        /// </summary>
        public static string UpdateText_Outdated {
            get {
                return ResourceManager.GetString("UpdateText_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the application has been installed. Restart the application to use the new version..
        /// </summary>
        public static string UpdateText_Updated {
            get {
                return ResourceManager.GetString("UpdateText_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove all data from matches that were previously entered. This data contains the set scores, the players, and everything that is entered manually. You can continue to use the program as before, but if you open a match day where results have already been entered, they will now be empty again.
        ///
        ///Are you sure you want to delete this data?.
        /// </summary>
        public static string Various_DeleteWarning {
            get {
                return ResourceManager.GetString("Various_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username/password combination is invalid!.
        /// </summary>
        public static string Various_InvalidLogin {
            get {
                return ResourceManager.GetString("Various_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while connecting to the competition website..
        /// </summary>
        public static string Various_NetworkError {
            get {
                return ResourceManager.GetString("Various_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a password..
        /// </summary>
        public static string Various_NoPassword {
            get {
                return ResourceManager.GetString("Various_NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a username..
        /// </summary>
        public static string Various_NoUsername {
            get {
                return ResourceManager.GetString("Various_NoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username/password combination is valid..
        /// </summary>
        public static string Various_ValidLogin {
            get {
                return ResourceManager.GetString("Various_ValidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All IP addresses.
        /// </summary>
        public static string WebService_AllIPs {
            get {
                return ResourceManager.GetString("WebService_AllIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the web service to work correctly, the administrator of this computer must first give explicit access to the current Windows-user to listen on the host and port you selected. Do you want ScoreSheet to request the permissions for user &apos;{0}&apos; to listen on the url &apos;{1}&apos;?.
        /// </summary>
        public static string WebService_UnblockAddressMessage {
            get {
                return ResourceManager.GetString("WebService_UnblockAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Wizard_AllFiles {
            get {
                return ResourceManager.GetString("Wizard_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Wizard_Cancel {
            get {
                return ResourceManager.GetString("Wizard_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Wizard_Close {
            get {
                return ResourceManager.GetString("Wizard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email data.
        /// </summary>
        public static string Wizard_Email {
            get {
                return ResourceManager.GetString("Wizard_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to email the data to the leisure competition responsibles..
        /// </summary>
        public static string Wizard_EmailDesc {
            get {
                return ResourceManager.GetString("Wizard_EmailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can email the data of multiple matches in one go. If you do not want to upload the data of certain matches, you can deselect them..
        /// </summary>
        public static string Wizard_EmailMessage {
            get {
                return ResourceManager.GetString("Wizard_EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export matches.
        /// </summary>
        public static string Wizard_Export {
            get {
                return ResourceManager.GetString("Wizard_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to export matches..
        /// </summary>
        public static string Wizard_ExportDesc {
            get {
                return ResourceManager.GetString("Wizard_ExportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can export the data of multiple matches in one go to the competition website. If you do not want to export the data of certain matches, you can deselect them..
        /// </summary>
        public static string Wizard_ExportMessage {
            get {
                return ResourceManager.GetString("Wizard_ExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update.
        /// </summary>
        public static string Wizard_InstallUpdate {
            get {
                return ResourceManager.GetString("Wizard_InstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to install a database update..
        /// </summary>
        public static string Wizard_InstallUpdateDesc {
            get {
                return ResourceManager.GetString("Wizard_InstallUpdateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select match type.
        /// </summary>
        public static string Wizard_MatchType {
            get {
                return ResourceManager.GetString("Wizard_MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to select the match type..
        /// </summary>
        public static string Wizard_MatchTypeDesc {
            get {
                return ResourceManager.GetString("Wizard_MatchTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new match day.
        /// </summary>
        public static string Wizard_NewMatchDay {
            get {
                return ResourceManager.GetString("Wizard_NewMatchDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date, and automatically get all matches of that match day..
        /// </summary>
        public static string Wizard_NewMatchDayDesc {
            get {
                return ResourceManager.GetString("Wizard_NewMatchDayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an existing file!.
        /// </summary>
        public static string Wizard_NoFileSelected {
            get {
                return ResourceManager.GetString("Wizard_NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No home matches were found on the day you selected..
        /// </summary>
        public static string Wizard_NoMatches {
            get {
                return ResourceManager.GetString("Wizard_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print documents.
        /// </summary>
        public static string Wizard_Print {
            get {
                return ResourceManager.GetString("Wizard_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to print referee score cards or match score sheets..
        /// </summary>
        public static string Wizard_PrintDesc {
            get {
                return ResourceManager.GetString("Wizard_PrintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player order you selected is invalid. Players must be ranked according to rank/index. Are you sure you want to continue with the chosen setup?.
        /// </summary>
        public static string Wizard_RankWarning {
            get {
                return ResourceManager.GetString("Wizard_RankWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover score sheets.
        /// </summary>
        public static string Wizard_Restore {
            get {
                return ResourceManager.GetString("Wizard_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to recover score sheets that were found in the backup directory..
        /// </summary>
        public static string Wizard_RestoreDesc {
            get {
                return ResourceManager.GetString("Wizard_RestoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select players.
        /// </summary>
        public static string Wizard_SelectPlayers {
            get {
                return ResourceManager.GetString("Wizard_SelectPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the players you want in the team. Drag the appropriate players from the list on the right to the boxes on the left..
        /// </summary>
        public static string Wizard_SelectPlayersDesc {
            get {
                return ResourceManager.GetString("Wizard_SelectPlayersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned the following errors:.
        /// </summary>
        public static string Wizard_ServerErrors {
            get {
                return ResourceManager.GetString("Wizard_ServerErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches with an unknown date.
        /// </summary>
        public static string Wizard_UnknownMatchDate {
            get {
                return ResourceManager.GetString("Wizard_UnknownMatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update database.
        /// </summary>
        public static string Wizard_Update {
            get {
                return ResourceManager.GetString("Wizard_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to update the database of the application..
        /// </summary>
        public static string Wizard_UpdateDesc {
            get {
                return ResourceManager.GetString("Wizard_UpdateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSheet update file.
        /// </summary>
        public static string Wizard_UpdateFile {
            get {
                return ResourceManager.GetString("Wizard_UpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To update the database through an update file, you must of course first have an update file. You must create this file on another computer that does have an internet connection.
        ///
        ///Start the ScoreSheet program on the computer with internet connection and update the database using the &apos;Update database via the Internet&apos; option. Once this is done, you can export that updated data to an update file by clicking on &apos;Options&apos;, &apos;Database updates&apos; in the menu, and then on &apos;Save update file&apos;. Give this update file a  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wizard_UpdateFileHelp {
            get {
                return ResourceManager.GetString("Wizard_UpdateFileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was successful!.
        /// </summary>
        public static string Wizard_UpdateSuccessful {
            get {
                return ResourceManager.GetString("Wizard_UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload data.
        /// </summary>
        public static string Wizard_Upload {
            get {
                return ResourceManager.GetString("Wizard_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this window to upload data to the competition website..
        /// </summary>
        public static string Wizard_UploadDesc {
            get {
                return ResourceManager.GetString("Wizard_UploadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload the data of multiple matches in one go to the competition website. If you do not want to upload the data of certain matches, you can deselect them..
        /// </summary>
        public static string Wizard_UploadMessage {
            get {
                return ResourceManager.GetString("Wizard_UploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been successfully uploaded!.
        /// </summary>
        public static string Wizard_UploadSuccessful {
            get {
                return ResourceManager.GetString("Wizard_UploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected matches with validation errors. Are you sure you want to continue?.
        /// </summary>
        public static string Wizard_ValidationWarning {
            get {
                return ResourceManager.GetString("Wizard_ValidationWarning", resourceCulture);
            }
        }
    }
}
