//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieterP.ScoreSheet.Localization.Views.Score {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieterP.ScoreSheet.Localization.Views.Score.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string Address_Title {
            get {
                return ResourceManager.GetString("Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONAL REMARKS.
        /// </summary>
        public static string Comments_Title {
            get {
                return ResourceManager.GetString("Comments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to play the matches two by two.
        /// </summary>
        public static string CompetitiveMatch_Agreed2v2 {
            get {
                return ResourceManager.GetString("CompetitiveMatch_Agreed2v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (article 6.32).
        /// </summary>
        public static string CompetitiveMatch_Article632 {
            get {
                return ResourceManager.GetString("CompetitiveMatch_Article632", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTAIN VISITORS.
        /// </summary>
        public static string CompetitiveMatch_AwayCaptain {
            get {
                return ResourceManager.GetString("CompetitiveMatch_AwayCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISITORS.
        /// </summary>
        public static string CompetitiveMatch_AwayTeam {
            get {
                return ResourceManager.GetString("CompetitiveMatch_AwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHIEF REFEREE.
        /// </summary>
        public static string CompetitiveMatch_ChiefReferee {
            get {
                return ResourceManager.GetString("CompetitiveMatch_ChiefReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTAIN HOME TEAM.
        /// </summary>
        public static string CompetitiveMatch_HomeCaptain {
            get {
                return ResourceManager.GetString("CompetitiveMatch_HomeCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME TEAM.
        /// </summary>
        public static string CompetitiveMatch_HomeTeam {
            get {
                return ResourceManager.GetString("CompetitiveMatch_HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM COMMISSIONER.
        /// </summary>
        public static string CompetitiveMatch_RoomCommissioner {
            get {
                return ResourceManager.GetString("CompetitiveMatch_RoomCommissioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string CompetitiveMatch_Yes {
            get {
                return ResourceManager.GetString("CompetitiveMatch_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string CompetitiveMatchInfo_Date {
            get {
                return ResourceManager.GetString("CompetitiveMatchInfo_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string CompetitiveMatchInfo_Level {
            get {
                return ResourceManager.GetString("CompetitiveMatchInfo_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Nbr.
        /// </summary>
        public static string CompetitiveMatchInfo_MatchId {
            get {
                return ResourceManager.GetString("CompetitiveMatchInfo_MatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string CompetitiveMatchInfo_Series {
            get {
                return ResourceManager.GetString("CompetitiveMatchInfo_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting time.
        /// </summary>
        public static string CompetitiveMatchInfo_StartHour {
            get {
                return ResourceManager.GetString("CompetitiveMatchInfo_StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of match.
        /// </summary>
        public static string CompetitiveMatchInfo_StopHour {
            get {
                return ResourceManager.GetString("CompetitiveMatchInfo_StopHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup.
        /// </summary>
        public static string CompetitiveMatchType_Cup {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub.
        /// </summary>
        public static string CompetitiveMatchType_Interclub {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Interclub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string CompetitiveMatchType_Men {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super.
        /// </summary>
        public static string CompetitiveMatchType_Super {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterans.
        /// </summary>
        public static string CompetitiveMatchType_Veterans {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Veterans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string CompetitiveMatchType_Women {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth.
        /// </summary>
        public static string CompetitiveMatchType_Youth {
            get {
                return ResourceManager.GetString("CompetitiveMatchType_Youth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double:.
        /// </summary>
        public static string DoublePlayerInfo_Double {
            get {
                return ResourceManager.GetString("DoublePlayerInfo_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate number:.
        /// </summary>
        public static string PersonDetails_AffiliateNumber {
            get {
                return ResourceManager.GetString("PersonDetails_AffiliateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club:.
        /// </summary>
        public static string PersonDetails_Club {
            get {
                return ResourceManager.GetString("PersonDetails_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubnr:.
        /// </summary>
        public static string PersonDetails_ClubId {
            get {
                return ResourceManager.GetString("PersonDetails_ClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PersonDetails_Name {
            get {
                return ResourceManager.GetString("PersonDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHES.
        /// </summary>
        public static string ScoreHeader_Matches {
            get {
                return ResourceManager.GetString("ScoreHeader_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POINTS.
        /// </summary>
        public static string ScoreHeader_Points {
            get {
                return ResourceManager.GetString("ScoreHeader_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETS.
        /// </summary>
        public static string ScoreHeader_Sets {
            get {
                return ResourceManager.GetString("ScoreHeader_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCH ORDER.
        /// </summary>
        public static string ScoreHeader_Title {
            get {
                return ResourceManager.GetString("ScoreHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute:.
        /// </summary>
        public static string SubstitutePlayerInfo_Substitute {
            get {
                return ResourceManager.GetString("SubstitutePlayerInfo_Substitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the player gives up after the game has already started.
        /// </summary>
        public static string SuspectSemantics_FFDesc {
            get {
                return ResourceManager.GetString("SuspectSemantics_FFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (number).
        /// </summary>
        public static string SuspectSemantics_Number {
            get {
                return ResourceManager.GetString("SuspectSemantics_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the score of the player.
        /// </summary>
        public static string SuspectSemantics_NumberDesc {
            get {
                return ResourceManager.GetString("SuspectSemantics_NumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID INPUT.
        /// </summary>
        public static string SuspectSemantics_Title {
            get {
                return ResourceManager.GetString("SuspectSemantics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention to the semantics of &apos;FF&apos; and &apos;WO&apos;. Forfait (FF) means that the match has started, but one of the players has given up. In this case, the other player is awarded the match as a win match. A Walk Over (WO) means that the match has not been played. In this case, the match does not count as an individual victory. An FF can therefore occur in any set (but no more than once per match). A WO can only occur in the first set of the competition..
        /// </summary>
        public static string SuspectSemantics_Warning {
            get {
                return ResourceManager.GetString("SuspectSemantics_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the game was not played (and does not count as an individual victory); a WO may only occur in the first set.
        /// </summary>
        public static string SuspectSemantics_WODesc {
            get {
                return ResourceManager.GetString("SuspectSemantics_WODesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap-
        ///tain.
        /// </summary>
        public static string TeamInfo_Captain {
            get {
                return ResourceManager.GetString("TeamInfo_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Id.
        /// </summary>
        public static string TeamInfo_ClubId {
            get {
                return ResourceManager.GetString("TeamInfo_ClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer
        ///number.
        /// </summary>
        public static string TeamInfo_ComputerNumber {
            get {
                return ResourceManager.GetString("TeamInfo_ComputerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF.
        /// </summary>
        public static string TeamInfo_Forfeit {
            get {
                return ResourceManager.GetString("TeamInfo_Forfeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string TeamInfo_Index {
            get {
                return ResourceManager.GetString("TeamInfo_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos
        ///ition.
        /// </summary>
        public static string TeamInfo_Position {
            get {
                return ResourceManager.GetString("TeamInfo_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string TeamInfo_Ranking {
            get {
                return ResourceManager.GetString("TeamInfo_Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamInfo_Team {
            get {
                return ResourceManager.GetString("TeamInfo_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ind.
        ///wins.
        /// </summary>
        public static string TeamInfo_Wins {
            get {
                return ResourceManager.GetString("TeamInfo_Wins", resourceCulture);
            }
        }
    }
}
