//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieterP.ScoreSheet.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieterP.ScoreSheet.Localization.Views.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program makes grateful use of the competition database managed by the KBTTB and the links to it made available by Gaëtan Frenoy. We also want to specifically thank Bruno Van Damme, David Waefelaer and Michèle Messiaen for their contribution to the program, as well as everyone who sent suggestions or reported errors..
        /// </summary>
        public static string AboutWindow_Attribution {
            get {
                return ResourceManager.GetString("AboutWindow_Attribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutWindow_Close {
            get {
                return ResourceManager.GetString("AboutWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0}, PieterP.be.
        /// </summary>
        public static string AboutWindow_Copyright {
            get {
                return ResourceManager.GetString("AboutWindow_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data directory.
        /// </summary>
        public static string AboutWindow_DataDirectory {
            get {
                return ResourceManager.GetString("AboutWindow_DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code for this program is available on the BitBucket link above. Do you want to help? Contact us!.
        /// </summary>
        public static string AboutWindow_OpenSource {
            get {
                return ResourceManager.GetString("AboutWindow_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program directory.
        /// </summary>
        public static string AboutWindow_ProgramDirectory {
            get {
                return ResourceManager.GetString("AboutWindow_ProgramDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string AboutWindow_Support {
            get {
                return ResourceManager.GetString("AboutWindow_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ScoreSheet....
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutWindow_Version {
            get {
                return ResourceManager.GetString("AboutWindow_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string AboutWindow_Website {
            get {
                return ResourceManager.GetString("AboutWindow_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AskPasswordWindow_Cancel {
            get {
                return ResourceManager.GetString("AskPasswordWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the username and the corresponding password that you want to use to connect to the competition website..
        /// </summary>
        public static string AskPasswordWindow_Description {
            get {
                return ResourceManager.GetString("AskPasswordWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username/password combination is invalid..
        /// </summary>
        public static string AskPasswordWindow_InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("AskPasswordWindow_InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AskPasswordWindow_Ok {
            get {
                return ResourceManager.GetString("AskPasswordWindow_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string AskPasswordWindow_Password {
            get {
                return ResourceManager.GetString("AskPasswordWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember username/password.
        /// </summary>
        public static string AskPasswordWindow_RememberLogin {
            get {
                return ResourceManager.GetString("AskPasswordWindow_RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string AskPasswordWindow_Username {
            get {
                return ResourceManager.GetString("AskPasswordWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred! This usually indicates an error in the program, or corrupt data files. If this error persists, it is best to contact the authors of this program at the email address score@pieterp.be In addition to a description of what you were doing when the error occurred occurred, you should also paste the text below in that email..
        /// </summary>
        public static string ErrorWindow_Description {
            get {
                return ResourceManager.GetString("ErrorWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ErrorWindow_Ok {
            get {
                return ResourceManager.GetString("ErrorWindow_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string ErrorWindow_UnexpectedError {
            get {
                return ResourceManager.GetString("ErrorWindow_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to the nature of the error, the program must be terminated..
        /// </summary>
        public static string ErrorWindow_UnrecoverableMessage {
            get {
                return ResourceManager.GetString("ErrorWindow_UnrecoverableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LogBook_Debug {
            get {
                return ResourceManager.GetString("LogBook_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string LogBook_Errors {
            get {
                return ResourceManager.GetString("LogBook_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string LogBook_Messages {
            get {
                return ResourceManager.GetString("LogBook_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show:.
        /// </summary>
        public static string LogBook_Show {
            get {
                return ResourceManager.GetString("LogBook_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string LogBook_Warnings {
            get {
                return ResourceManager.GetString("LogBook_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logbook.
        /// </summary>
        public static string MainWindow_LogBook {
            get {
                return ResourceManager.GetString("MainWindow_LogBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ScoreSheet.
        /// </summary>
        public static string MainWindow_MenuAbout {
            get {
                return ResourceManager.GetString("MainWindow_MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make official fields read-only.
        /// </summary>
        public static string MainWindow_MenuCanChangeOfficialFields {
            get {
                return ResourceManager.GetString("MainWindow_MenuCanChangeOfficialFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MainWindow_MenuClose {
            get {
                return ResourceManager.GetString("MainWindow_MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close _all.
        /// </summary>
        public static string MainWindow_MenuCloseAll {
            get {
                return ResourceManager.GetString("MainWindow_MenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition day (for a single division).
        /// </summary>
        public static string MainWindow_MenuDivisionDay {
            get {
                return ResourceManager.GetString("MainWindow_MenuDivisionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email leisure competition results.
        /// </summary>
        public static string MainWindow_MenuEmail {
            get {
                return ResourceManager.GetString("MainWindow_MenuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_MenuExit {
            get {
                return ResourceManager.GetString("MainWindow_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export matches.
        /// </summary>
        public static string MainWindow_MenuExport {
            get {
                return ResourceManager.GetString("MainWindow_MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainWindow_MenuFile {
            get {
                return ResourceManager.GetString("MainWindow_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string MainWindow_MenuFullScreen {
            get {
                return ResourceManager.GetString("MainWindow_MenuFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainWindow_MenuHelp {
            get {
                return ResourceManager.GetString("MainWindow_MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition day (for this club).
        /// </summary>
        public static string MainWindow_MenuMatchDay {
            get {
                return ResourceManager.GetString("MainWindow_MenuMatchDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MainWindow_MenuNew {
            get {
                return ResourceManager.GetString("MainWindow_MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MainWindow_MenuOpen {
            get {
                return ResourceManager.GetString("MainWindow_MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MainWindow_MenuOptions {
            get {
                return ResourceManager.GetString("MainWindow_MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print.
        /// </summary>
        public static string MainWindow_MenuPrint {
            get {
                return ResourceManager.GetString("MainWindow_MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program updates.
        /// </summary>
        public static string MainWindow_MenuProgramUpdates {
            get {
                return ResourceManager.GetString("MainWindow_MenuProgramUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_MenuSave {
            get {
                return ResourceManager.GetString("MainWindow_MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MainWindow_MenuSaveAs {
            get {
                return ResourceManager.GetString("MainWindow_MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save update file.
        /// </summary>
        public static string MainWindow_MenuSaveUpdateFile {
            get {
                return ResourceManager.GetString("MainWindow_MenuSaveUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unofficial score sheet.
        /// </summary>
        public static string MainWindow_MenuScoreSheet {
            get {
                return ResourceManager.GetString("MainWindow_MenuScoreSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change _settings.
        /// </summary>
        public static string MainWindow_MenuSettings {
            get {
                return ResourceManager.GetString("MainWindow_MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Database updates.
        /// </summary>
        public static string MainWindow_MenuUpdate {
            get {
                return ResourceManager.GetString("MainWindow_MenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update database.
        /// </summary>
        public static string MainWindow_MenuUpdateDatabase {
            get {
                return ResourceManager.GetString("MainWindow_MenuUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to competition website.
        /// </summary>
        public static string MainWindow_MenuUpload {
            get {
                return ResourceManager.GetString("MainWindow_MenuUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logbook.
        /// </summary>
        public static string MainWindow_OpenLogbook {
            get {
                return ResourceManager.GetString("MainWindow_OpenLogbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainWindow_PopupMenuClose {
            get {
                return ResourceManager.GetString("MainWindow_PopupMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string MainWindow_PopupMenuPrint {
            get {
                return ResourceManager.GetString("MainWindow_PopupMenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart required.
        /// </summary>
        public static string MainWindow_RestartRequired {
            get {
                return ResourceManager.GetString("MainWindow_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a language/translation error.
        /// </summary>
        public static string MainWindow_SubmitTranslationError {
            get {
                return ResourceManager.GetString("MainWindow_SubmitTranslationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string MainWindow_Zoom {
            get {
                return ResourceManager.GetString("MainWindow_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SaveWindow_Cancel {
            get {
                return ResourceManager.GetString("SaveWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following match(es) have not yet been saved. Do you want to save the changes to these matches?.
        /// </summary>
        public static string SaveWindow_Description {
            get {
                return ResourceManager.GetString("SaveWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all.
        /// </summary>
        public static string SaveWindow_DiscardAll {
            get {
                return ResourceManager.GetString("SaveWindow_DiscardAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string SaveWindow_SaveAll {
            get {
                return ResourceManager.GetString("SaveWindow_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSheet is automatically updated in the background when a new version is available. However, if this computer is not always online, it may be necessary to manually start the update through this window..
        /// </summary>
        public static string UpdateAppWindow_AutomaticUpdates {
            get {
                return ResourceManager.GetString("UpdateAppWindow_AutomaticUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UpdateAppWindow_Close {
            get {
                return ResourceManager.GetString("UpdateAppWindow_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program updates provide access to new features, and can also eliminate bugs found in earlier versions of ScoreSheet. It is therefore highly recommended to always update to the latest version..
        /// </summary>
        public static string UpdateAppWindow_Description {
            get {
                return ResourceManager.GetString("UpdateAppWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ScoreSheet.
        /// </summary>
        public static string UpdateAppWindow_Title {
            get {
                return ResourceManager.GetString("UpdateAppWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a blank score sheet.
        /// </summary>
        public static string WelcomeWindow_BlankMatch {
            get {
                return ResourceManager.GetString("WelcomeWindow_BlankMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data must be entered manually; choose this option for non-competition matches (eg friends matches)..
        /// </summary>
        public static string WelcomeWindow_BlankMatchDesc {
            get {
                return ResourceManager.GetString("WelcomeWindow_BlankMatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the thing that you want to do..
        /// </summary>
        public static string WelcomeWindow_Message {
            get {
                return ResourceManager.GetString("WelcomeWindow_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new match day.
        /// </summary>
        public static string WelcomeWindow_NewMatchDay {
            get {
                return ResourceManager.GetString("WelcomeWindow_NewMatchDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date, and automatically get all matches on that match day..
        /// </summary>
        public static string WelcomeWindow_NewMatchDayDesc {
            get {
                return ResourceManager.GetString("WelcomeWindow_NewMatchDayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing score sheet.
        /// </summary>
        public static string WelcomeWindow_OpenMatch {
            get {
                return ResourceManager.GetString("WelcomeWindow_OpenMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a score sheet that was previously saved..
        /// </summary>
        public static string WelcomeWindow_OpenMatchDesc {
            get {
                return ResourceManager.GetString("WelcomeWindow_OpenMatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! What do you want to do?.
        /// </summary>
        public static string WelcomeWindow_Title {
            get {
                return ResourceManager.GetString("WelcomeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update database.
        /// </summary>
        public static string WelcomeWindow_UpdateDb {
            get {
                return ResourceManager.GetString("WelcomeWindow_UpdateDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the database of this program. This data includes member lists and match dates..
        /// </summary>
        public static string WelcomeWindow_UpdateDbDesc {
            get {
                return ResourceManager.GetString("WelcomeWindow_UpdateDbDesc", resourceCulture);
            }
        }
    }
}
