//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PieterP.ScoreSheet.Installer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PieterP.ScoreSheet.Installer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made.
        /// </summary>
        public static string App_ChangesMade {
            get {
                return ResourceManager.GetString("App_ChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes made.
        /// </summary>
        public static string App_NoChangesMade {
            get {
                return ResourceManager.GetString("App_NoChangesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS 1.2 has been successfully switched on! You may need to restart the computer for the changes to take effect..
        /// </summary>
        public static string App_TlsEnabled {
            get {
                return ResourceManager.GetString("App_TlsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while turning on TLS 1.2. You may not have the correct rights to make these changes..
        /// </summary>
        public static string App_TlsNotEnabled {
            get {
                return ResourceManager.GetString("App_TlsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string InstallationComplete_Close {
            get {
                return ResourceManager.GetString("InstallationComplete_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string InstallationComplete_Error {
            get {
                return ResourceManager.GetString("InstallationComplete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem occurred during the installation of ScoreSheet. If this problem persists, please contact the program managers at score@pieterp.be..
        /// </summary>
        public static string InstallationComplete_ErrorMessage {
            get {
                return ResourceManager.GetString("InstallationComplete_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of ScoreSheet has been successfully completed..
        /// </summary>
        public static string InstallationComplete_Message {
            get {
                return ResourceManager.GetString("InstallationComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        public static string InstallationComplete_Ready {
            get {
                return ResourceManager.GetString("InstallationComplete_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ScoreSheet.
        /// </summary>
        public static string InstallationComplete_Start {
            get {
                return ResourceManager.GetString("InstallationComplete_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing user interface.
        /// </summary>
        public static string Installing_GUI {
            get {
                return ResourceManager.GetString("Installing_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &quot;GUI&quot; installation package..
        /// </summary>
        public static string Installing_GUINotFound {
            get {
                return ResourceManager.GetString("Installing_GUINotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing launcher.
        /// </summary>
        public static string Installing_Launcher {
            get {
                return ResourceManager.GetString("Installing_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &quot;LAUNCHER&quot; installation package..
        /// </summary>
        public static string Installing_LauncherNotFound {
            get {
                return ResourceManager.GetString("Installing_LauncherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installer is now installing ScoreSheet. Please be patient..
        /// </summary>
        public static string Installing_Message {
            get {
                return ResourceManager.GetString("Installing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating desktop shortcut.
        /// </summary>
        public static string Installing_ShortcutDesktop {
            get {
                return ResourceManager.GetString("Installing_ShortcutDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating start menu shortcut.
        /// </summary>
        public static string Installing_ShortcutStartMenu {
            get {
                return ResourceManager.GetString("Installing_ShortcutStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string Installing_Title {
            get {
                return ResourceManager.GetString("Installing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreSheet Installer.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install directory.
        /// </summary>
        public static string Prereq_Directory {
            get {
                return ResourceManager.GetString("Prereq_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install ScoreSheet.
        /// </summary>
        public static string Prereq_Install {
            get {
                return ResourceManager.GetString("Prereq_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program will install ScoreSheet on your system..
        /// </summary>
        public static string Prereq_Message {
            get {
                return ResourceManager.GetString("Prereq_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8 or higher required.
        /// </summary>
        public static string Prereq_Netfx {
            get {
                return ResourceManager.GetString("Prereq_Netfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download the .NET Framework 4.8.
        /// </summary>
        public static string Prereq_NetfxDownload {
            get {
                return ResourceManager.GetString("Prereq_NetfxDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the .NET Framework installed on this computer is too old. You must install the .NET Framework version 4.8 or higher..
        /// </summary>
        public static string Prereq_NetfxErr {
            get {
                return ResourceManager.GetString("Prereq_NetfxErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of the .NET Framework is sufficient..
        /// </summary>
        public static string Prereq_NetfxOk {
            get {
                return ResourceManager.GetString("Prereq_NetfxOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more information about this.
        /// </summary>
        public static string Prereq_ReadMore {
            get {
                return ResourceManager.GetString("Prereq_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System requirements.
        /// </summary>
        public static string Prereq_Requirements {
            get {
                return ResourceManager.GetString("Prereq_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ScoreSheet.
        /// </summary>
        public static string Prereq_Title {
            get {
                return ResourceManager.GetString("Prereq_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS 1.2 or higher required.
        /// </summary>
        public static string Prereq_Tls {
            get {
                return ResourceManager.GetString("Prereq_Tls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TLS 1.2 support.
        /// </summary>
        public static string Prereq_TlsEnable {
            get {
                return ResourceManager.GetString("Prereq_TlsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support for TLS 1.2 or higher is not enabled on this system. As a result, ScoreSheet may not be able to download data from the competition website. Fortunately, Windows 7 does support this protocol, so you can simply enable it..
        /// </summary>
        public static string Prereq_TlsErrW7 {
            get {
                return ResourceManager.GetString("Prereq_TlsErrW7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Vista does not support TLS 1.2 by default, but it can be turned on in an unofficial way. The ScoreSheet download page contains more information about this..
        /// </summary>
        public static string Prereq_TlsErrWV {
            get {
                return ResourceManager.GetString("Prereq_TlsErrWV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This system supports TLS 1.2 or higher..
        /// </summary>
        public static string Prereq_TlsOk {
            get {
                return ResourceManager.GetString("Prereq_TlsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: you can install ScoreSheet, but as long as the above requirements are not met, ScoreSheet may not work correctly!.
        /// </summary>
        public static string Prereq_Warning {
            get {
                return ResourceManager.GetString("Prereq_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 7 or higher required.
        /// </summary>
        public static string Prereq_Windows {
            get {
                return ResourceManager.GetString("Prereq_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re running on an old version of Windows. This version is no longer supported..
        /// </summary>
        public static string Prereq_WindowsErr {
            get {
                return ResourceManager.GetString("Prereq_WindowsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Windows is sufficient..
        /// </summary>
        public static string Prereq_WindowsOk {
            get {
                return ResourceManager.GetString("Prereq_WindowsOk", resourceCulture);
            }
        }
    }
}
